### PR TITLE
These changes seem useful to merge-in

### PR DESCRIPTION
**Pull request by birbilis**

### CODE REVIEW

**Comment by birbilis** [comment]
Closing the Pull request for now, since it seems ludo6557's version mistakenly recognizes wii balance board as wiimote device, whereas the original code (the one from Google code that is the same as the one here [as it is currently] from what I understand) recognizes it correctly

**Comment by FrozenCow** [comment]
Best would be to split this into separate pull requests, since this is about different features/bugs. That way we can discuss each one separately.

Just to give some of my thoughts:
- I see no problems with the .NET 4 and/or x86/x64 changes.
- I see no problems with the new PID.
- Prioritizing MsHid above MsBluetooth seems wong. MsBluetooth will never be picked on Windows, since all machines always support MsHid. In addition, MsHid doesn't support automatically connecting to a Wiimote, whereas MsBluetooth does. Is MsBluetooth indeed in such a broken state that it isn't usable?
- Removing update from MsHid's factory is indeed the correct fix. No need to comment it.
- I'm not sure why WiiDeviceLibrary-Unity includes all files from the library, instead of just referencing the library. Is referencing illegal on Unity?
- Do not commit the `.pdb` and `.dll` (or anything else from bin/ or obj/).
- 2 directories seem to be committed: `wiidevicelibrary-Unity` and `WiiDeviceLibrary-Unity`. Please reset/unstage all of the files, check the casing and add the files to the repository again.

Again, best would be to create a PR for each feature/bug separately, that makes it easier to handle and communicate about them.

**Comment by birbilis** [comment]
which change do you think cause the wrong detection of the balance board that I mention above?
copying from https://github.com/FrozenCow/wiidevicelibrary/issues/1#issuecomment-131061759 my comment:
do you have any insight on which change from the ones ludo6577 did causes the misrecognition of the balance board as "wiimote device"? Is it the "•Prioritizing MsHid above MsBluetooth seems wong. MsBluetooth will never be picked on Windows, since all machines always support MsHid" that you mention at #2 ? Sounds like that is the issue. After the wrong recognition the GUI example doesn't show the balance board UI, but other

**Comment by birbilis** [comment]
another thing is that I see that once you do a Pull Request, GitHub keeps on adding to the PR any new commits you do automatically. So is it possible at all to do separate PRs with a set of changes and then freeze it? Else they'll have to do each change, then PR, then have you accept/merge, then proceed to next set of changes etc. 

maybe one can pick specific commits from Ludo's repository only, but not sure if each commit he had done was only handling one issue.

**Comment by FrozenCow** [comment]
If anything, the PID change seems the most related. Though I'm not sure how that would detect it wrongly. Does the balanceboard broadcast 2 different PIDs by any chance?

Otherwise, I would suggest trying the different commits to see which one fails. [git-bisect](https://git-scm.com/book/en/v2/Git-Tools-Debugging-with-Git#Binary-Search) might help with that.

About the PRs: you need to create separate (feature) branches for each change. Push each branch to your fork, GitHub will suggest to create a PR for each of the branches. After that you can iterate on each change by adding commits to that branch.

**Comment by birbilis** [comment]
I think the wrong detection is due to the order the factories are checked by @ludo6577, assuming the MsHid is limited and only sees the balance board as a "wiimote device" (human interface device). I hadn't noticed MsHid though in the code from a quick look I had taken, only read about it from your comments

**Pull request closed without merging**
